title: Waze Ireland WME Datasets
email: chris@cw1998.uk
description: >- # this means to ignore newlines until "baseurl:"
  A website that allows you to find and download resources for use in WME in Ireland.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  counties:
    output: true

# Build settings
markdown: kramdown
# theme: govuk-frontend-theme-jekyll
plugins:
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
